### ISSUE TITLE
ChromeDriver Update Error

### ISSUE THREAD

**Issue by mksharmamk** [Swimburger/DownloadChromeDriverSample#2]
Thank you,

Facing Below Error 
ChromeDriver Update Error with new code

![image](https://github.com/Swimburger/DownloadChromeDriverSample/assets/31514812/ebda0d7b-1d70-401d-88f1-9e3d92f82f11)

Warm regards,
mk.

**Comment by Swimburger** [comment]
The process for getting the Chrome version would've already exited when telling to kill the process, hence the error.
I removed the process kill and it works.

https://github.com/Swimburger/DownloadChromeDriverSample/pull/3
